config/routes.rb
Cashflow::Application.routes.draw do
  get "main/index"

  scope 'api' do
    get    'ledgers'     => 'Ledger#list'
    post   'ledgers'     => 'Ledger#create'
    get    'ledgers/:id' => 'Ledger#show'
    put    'ledgers/:id' => 'Ledger#update'
    delete 'ledgers/:id' => 'Ledger#delete'

    get    'accounts'     => 'Account#list'
    post   'accounts'     => 'Account#create'
    get    'accounts/:id' => 'Account#show'
    put    'accounts/:id' => 'Account#update'
    delete 'accounts/:id' => 'Account#delete'

    get    'postings'     => 'Posting#list'
    post   'postings'     => 'Posting#create'
    get    'postings/:id' => 'Posting#show'
    put    'postings/:id' => 'Posting#update'
    delete 'postings/:id' => 'Posting#delete'

    get    'banks'     => 'BankAccount#list'
    post   'banks'     => 'BankAccount#create'
    get    'banks/:id' => 'BankAccount#show'
    get    'banks/:id/balance' => 'BankAccount#balance'
    get    'banks/:id/balance_range' => 'BankAccount#balance_range'
    put    'banks/:id' => 'BankAccount#update'
    delete 'banks/:id' => 'BankAccount#delete'

    get    'banks/:bank_id/transactions'     => 'BankTransaction#list'
    post   'banks/:bank_id/transactions'     => 'BankTransaction#create'
    get    'banks/:bank_id/transactions/:id' => 'BankTransaction#show'
    put    'banks/:bank_id/transactions/:id' => 'BankTransaction#update'
    delete 'banks/:bank_id/transactions/:id' => 'BankTransaction#delete'
    post   'banks/:bank_id/transactions/import' => 'BankTransaction#import'

  end

  root :to => 'main#index'

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base

  has_many :bank_transactions

  validates :bank,           :presence => true
  validates :name,           :presence => true
  validates :initial_cents,  :presence => true
  validates :account_number, :presence => true,
                             :numericality => true,
                             :length => { minimum: 5 }

  # use Money gem to handle amount (composed of cents and currency fields)
  composed_of :opening_balance,
    :class_name => "Money",
    :mapping => [%w(initial_cents cents), %w(currency currency_as_string)],
    :constructor => Proc.new { |cents, currency| Money.new(cents || 0, currency || Money.default_currency) },
    :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : raise(ArgumentError, "Can't convert #{value.class} to Money") }


  # calculates and returns account balance. If no date is specified
  # then current date is assumed.
  def balance(date=nil)
    date ||= Time.now.strftime("%Y-%m-%d")
    validate_date(date)

    transaction_sum = BankTransaction.where("bank_account_id = ? AND date <= ?", id, date).sum('cents')
    sum = initial_cents + transaction_sum
    balance = get_formatted_balance(date, sum, currency)
  end

  # returns the balance in the given date range for each
  # day where there is at least one transaction - including an additional
  # starting balance on the 'from_date' if no transactions on that day, and 
  # also additional final balance if no transactions on that day.
  def balance_range(from_date, to_date)
    parsed_from_date = validate_date(from_date)
    parsed_to_date = validate_date(to_date)
    return [] if from_date > to_date

    balance = []
    transactions = BankTransaction.select("date(date) as date, currency, sum(cents) as cents").group("date(date)").having("bank_account_id = ? AND date >= ? AND date <= ?", id, from_date, to_date)
    sum = initial_cents
    transactions.each do |t|
      sum += t.cents
      balance << get_formatted_balance(t.date, sum, t.currency)
    end

    if balance.empty? || balance.first[:date] != parsed_from_date
      balance.unshift balance(from_date)
    end

    if balance.empty? || balance.last[:date] != parsed_to_date
      balance << balance(to_date)
    end

    balance
  end

  def get_formatted_balance(date, sum, currency)
    amount = Money.new(sum, currency)
    {
      date: date,
      amount: amount.dollars,
      cents:  amount.cents,
      currency: amount.currency.iso_code
    }
  end

  def as_json(*args)
    hash = super(*args)
    hash['opening_balance'] = opening_balance.dollars
    return hash
  end


  private

  # validates date format and also that date is not in the future.
  def validate_date(date)
    begin
      date = Date.parse(date)
      raise if date > Date.today
    rescue
      raise ApplicationController::InvalidDateError.new('invalid date')
    end
    date
  end
end

app/controllers/bank_account_controller.rb
class BankAccountController < ApplicationController

  def list
    list = BankAccount.all
    render :json => list
  end

  def balance
    balance = BankAccount.find(params[:id]).balance(params[:date])
    render :json => balance
  end

  def balance_range
    balance = BankAccount.find(params[:id]).balance_range(params[:from_date], params[:to_date])
    render :json => balance
  end

  def show
    item = BankAccount.find(params[:id])
    render :json => item
  end

  def create
    item = BankAccount.new(params[:bank_account])

    if item.save
      render json: item, status: :created, location: "bank-accounts/#{item.id}"
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def update
    item = BankAccount.find(params[:id])

    if item.update_attributes(params[:bank_account])
      render json: item
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def delete
    item = BankAccount.find(params[:id])
    if item
      item.destroy
      render json: {}
    else
      render json: {}, status: :unprocessable_entity
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  # GET /bank_accounts
  # GET /bank_accounts.xml
  def index
    @bank_accounts = BankAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bank_accounts }
    end
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.xml
  def show
    @bank_account = BankAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bank_account }
    end
  end

  # GET /bank_accounts/new
  # GET /bank_accounts/new.xml
  def new
    @bank_account = BankAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bank_account }
    end
  end

  # GET /bank_accounts/1/edit
  def edit
    @bank_account = BankAccount.find(params[:id])
  end

  # POST /bank_accounts
  # POST /bank_accounts.xml
  def create
    @bank_account = BankAccount.new(params[:bank_account])

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to(@bank_account, :notice => 'Bank account was successfully created.') }
        format.xml  { render :xml => @bank_account, :status => :created, :location => @bank_account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bank_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bank_accounts/1
  # PUT /bank_accounts/1.xml
  def update
    @bank_account = BankAccount.find(params[:id])

    respond_to do |format|
      if @bank_account.update_attributes(params[:bank_account])
        format.html { redirect_to(@bank_account, :notice => 'Bank account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bank_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.xml
  def destroy
    @bank_account = BankAccount.find(params[:id])
    @bank_account.destroy

    respond_to do |format|
      format.html { redirect_to(bank_accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bank %><br />
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :account_number %><br />
    <%= f.text_field :account_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing bank_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/index.html.erb
<h1>Listing bank_accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bank</th>
    <th>Account number</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bank_accounts.each do |bank_account| %>
  <tr>
    <td><%= bank_account.name %></td>
    <td><%= bank_account.bank %></td>
    <td><%= bank_account.account_number %></td>
    <td><%= bank_account.description %></td>
    <td><%= link_to 'Show', bank_account %></td>
    <td><%= link_to 'Edit', edit_bank_account_path(bank_account) %></td>
    <td><%= link_to 'Destroy', bank_account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bank account', new_bank_account_path %>

app/views/bank_accounts/new.html.erb
<h1>New bank_account</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bank_account.name %>
</p>

<p>
  <b>Bank:</b>
  <%= @bank_account.bank %>
</p>

<p>
  <b>Account number:</b>
  <%= @bank_account.account_number %>
</p>

<p>
  <b>Description:</b>
  <%= @bank_account.description %>
</p>


<%= link_to 'Edit', edit_bank_account_path(@bank_account) %> |
<%= link_to 'Back', bank_accounts_path %>